[2024-12-22 14:10:19,133] root - INFO - >>>> stage Data ingestion pipeline started <<<<<
[2024-12-22 14:10:19,133] root - ERROR - Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x0000019DBC68A340> does not match annotation type <class 'pathlib.Path'>
Traceback (most recent call last):
  File "D:\ML_Projects\End_to_end\Text_Classification\main.py", line 10, in <module>
    obj.main()
  File "D:\ML_Projects\End_to_end\Text_Classification\hate\pipeline\data_ingestion.py", line 23, in main
    raise e
  File "D:\ML_Projects\End_to_end\Text_Classification\hate\pipeline\data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML_Projects\End_to_end\Text_Classification\hate\config\configuration.py", line 8, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ML\envs\textClassifier\Lib\site-packages\ensure\main.py", line 833, in __call__
    raise EnsureError(msg.format(arg=arg, f=self.f, t=templ, valt=type(value)))
ensure.main.EnsureError: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x0000019DBC68A340> does not match annotation type <class 'pathlib.Path'>
